import java.math.BigInteger;

/*
    Rule 04. Characters and Strings (STR)
    STR03-J. Do not encode noncharacter data as a string.

    This compliant solution first produces a String representation of the BigInteger object 
    and then converts the String object to a byte array. This process is then reversed. 
    Because the textual representation in the String object is generated by the 
    BigInteger class, it contains valid character data in the default character set.
*/

public class R04_STR03_J 
{
    public static void main(String[] args) 
    {
      BigInteger x = new BigInteger("530500452766");
      String s = x.toString();  // Valid character data
      byte[] byteArray = s.getBytes();
      String ns = new String(byteArray); 
      x = new BigInteger(ns);
      System.out.println(x);
    }
}